id: A4C8C8687
title: fAA27
type: translation
source_metadata:
  languages:
  - en
  - bo
  - zh
  - sa
  - fr
  datatype: PlainText
  created_at: 2022-05-27 19:49:38.293258
  last_modified_at: 2022-05-27 19:49:38.293264
