id: A4C8C8687
title: fAE79
type: translation
source_metadata:
  languages:
  - en
  - bo
  - zh
  - sa
  - fr
  datatype: PlainText
  created_at: 2022-05-27 19:49:38.300484
  last_modified_at: 2022-05-27 19:49:38.300489
